# Generated by Django 6.0.6 on 2026-06-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nilpoint', '0004_remove_game_name_game_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CypherpunkGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nilpoint.game')),
            ],
            bases=('nilpoint.game',),
        ),
    ]
