# Generated by Django 6.0.6 on 2026-06-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cypherpunk', '0001_initial'),
        ('nilpoint', '0017_game_default_location_graphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='nilpoint.playercharacter')),
            ],
        ),
    ]
