# Generated by Django 6.0.6 on 2026-06-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cypherpunk', '0002_module_deck'),
        ('nilpoint', '0017_game_default_location_graphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CypherpunkPC',
            fields=[
                ('playercharacter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nilpoint.playercharacter')),
            ],
            bases=('nilpoint.playercharacter',),
        ),
        migrations.AlterField(
            model_name='deck',
            name='player_character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='cypherpunk.cypherpunkpc'),
        ),
    ]
