# Generated by Django 6.0.6 on 2026-06-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cypherpunk', '0003_cypherpunkpc_alter_deck_player_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='deck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cypherpunk.deck'),
            preserve_default=False,
        ),
    ]
