# Generated by Django 6.0.6 on 2026-06-23 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cypherpunk', '0004_module_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cypherpunk.module')),
            ],
            bases=('cypherpunk.module',),
        ),
    ]
