# Generated by Django 6.0.6 on 2026-06-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0002_alter_game_name_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='handle',
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilpoint.player')),
            ],
        ),
    ]
