# Generated by Django 6.0.6 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0003_remove_player_handle_playercharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='instance_name',
            field=models.CharField(default='None', help_text='The name of this game instance', max_length=100),
            preserve_default=False,
        ),
    ]
