# Generated by Django 6.0.6 on 2026-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0004_remove_game_name_game_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_game_type',
            field=models.CharField(default=None, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
