# Generated by Django 6.0.6 on 2026-06-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0006_alter_player_user_alter_playercharacter_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_characters', to='nilpoint.game'),
            preserve_default=False,
        ),
    ]
