# Generated by Django 6.0.6 on 2026-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0007_playercharacter_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instance_name',
            field=models.TextField(blank=True, help_text='Description of the game instance'),
        ),
    ]
