# Generated by Django 6.0.6 on 2026-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0008_alter_game_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='instance_description',
            field=models.TextField(blank=True, help_text='Description of the game instance'),
        ),
        migrations.AlterField(
            model_name='game',
            name='instance_name',
            field=models.CharField(help_text='The name of this game instance', max_length=100),
        ),
    ]
