# Generated by Django 6.0.6 on 2026-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0009_game_instance_description_alter_game_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nilpoint_slug',
            field=models.SlugField(default='', help_text='A unique string that identifies this game in URLs', unique=True),
            preserve_default=False,
        ),
    ]
