# Generated by Django 6.0.6 on 2026-06-13 06:18

# Solves issue with existing games not having a nilpoint_slug, which
# arrives and needs to be unique. It's added in the previous migration
# without the unuique constraint. Here a unique value is added, then
# the null and unique constraints are applied ater this data migration

from django.db import migrations


def populate_slug(apps, schema_editor):
    Game = apps.get_model("nilpoint", "Game")
    for obj in Game.objects.all():
        obj.nilpoint_slug = f"temp-slug-{obj.id}"
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("nilpoint", "0010_game_nilpoint_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slug),
    ]
