# Generated by Django 6.0.6 on 2026-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nilpoint", "0011_auto_20260613_0618"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="nilpoint_slug",
            field=models.SlugField(
                help_text="A unique string that identifies this game in URLs",
                unique=True,
                null=False,
            ),
        ),
    ]
