# Generated by Django 6.0.6 on 2026-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0012_alter_game_nilpoint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_multiple_characters',
            field=models.BooleanField(default=False, help_text='Can a player have multiple player characters in this game?'),
        ),
    ]
