# Generated by Django 6.0.6 on 2026-06-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0013_game_allow_multiple_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name of the place, will be shown to the user', max_length=100)),
                ('instance_description', models.TextField(blank=True, help_text='Description of the location')),
                ('graphic', models.CharField(blank=True, help_text='Static path for the graphic', max_length=100, null=True)),
                ('initial', models.BooleanField(default=False, help_text='Is this the starting location?')),
            ],
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nilpoint.location'),
        ),
    ]
