# Generated by Django 6.0.6 on 2026-06-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0014_location_playercharacter_current_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='instance_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='nilpoint.game'),
            preserve_default=False,
        ),
    ]
