# Generated by Django 6.0.6 on 2026-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0015_rename_instance_description_location_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('initial', True)), fields=('game',), name='unique_initial_location_per_game'),
        ),
    ]
