# Generated by Django 6.0.6 on 2026-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0016_location_unique_initial_location_per_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='default_location_graphic',
            field=models.CharField(blank=True, default=None, help_text='Static path to default location graphic. Uses nilpoint default if not set.', max_length=100, null=True),
        ),
    ]
