# Generated by Django 6.0.6 on 2026-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0017_game_default_location_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='css',
            field=models.CharField(blank=True, help_text='Path for including game-specific css', max_length=100, null=True),
        ),
    ]
